### ISSUE TITLE
Body (Inferred)

### ISSUE THREAD

**Issue by jon-peel** [AngelMunoz/NetSixSamples#1]
Hello (This is not an issue, more of a question)

I have copied elements from this repo while trying to use Minimal API in F#

If I try to use injection on a post, I get an error saying the body is inferred (example below).
Have you seen this, have you found a way around it?

For now, I am probably going to stick with Controllers.
I have looked at Giraffe and Saturn, but I am not that big a fan of their syntaxes.
And I couldn't find a way to get Swagger to work with them (which I use for client generation)

As I said, this is not an "issue", I am only curious to know if you have found a solution to this.

```fsharp
let private addTodo =
    Func<ILogger, Todo, bool>
        (fun logger -> fun  todo ->
            logger.LogInformation("Save todo", todo)            
            true)
```

**Comment by AngelMunoz** [comment]
Hello there, Hmmm by the looks of it it seems you're trying to return a function from the function

I think the signature should be like this

```fsharp
Func<ILogger, Todo, bool>(
  fun logger todo ->
    logger.LogInformation("Save todo", todo)
    true
)
```
both `ILogger` and `Todo` are parameters of the same function, so no need to add an extra function (the second -> fun todo ->)

> I have looked at Giraffe and Saturn, but I am not that big a fan of their syntaxes.

I understand it, the routing is quite different. I wish it was Pipe based rather than composition based it would look simpler.

In case you were wondering how it would look in Giraffe/Saturn, the handler would be like this

```fsharp
let handler: HttpHandler =
  fun next ctx ->
    let logger = ctx.getLogger("Handler")
    // let service = ctx.getService<IMyService>()

    let todo = ctx.bindForm<Todo>() // or ctx.bindJson<Todo>()
    logger.LogInformation("Save todo", todo)
    true
```
it's a little bit more explicit indeed, but I guess overall they are very similar



in any case DI should work there's a sample here https://github.com/AngelMunoz/NetSixSamples/blob/main/Newishfs/Todos.fs#L19-L21

feel free to ping back if something is not working fine

**Comment by jon-peel** [comment]
Thank you for your response.

After some testing, it turned out my issue was the non-generic ILogger.
The DI did not know how to resolve it 🤷🏻‍♂️

**Comment by AngelMunoz** [comment]
Ah! Cryptic errors from common use cases, one has to love those right?

I'm glad you could fix that, feel free to ping back if needed I'll try to help out 😁
